# Generated by Django 2.1.1 on 2018-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20181011_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='www.naver.com', max_length=150),
        ),
    ]
