# Generated by Django 2.1.1 on 2018-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20181112_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nick',
            field=models.CharField(default='', max_length=10),
        ),
    ]
