# Generated by Django 2.1.1 on 2018-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20181120_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('color', models.CharField(default='white', max_length=30)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('link', models.URLField(default='www.naver.com', max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
