# Generated by Django 2.1.1 on 2018-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('detail', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
