# Generated by Django 2.0.13 on 2022-12-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_future'),
    ]

    operations = [
        migrations.CreateModel(
            name='en_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('color', models.CharField(default='white', max_length=30)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('link', models.URLField(default='www.naver.com', max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='en_Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('detail', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='en_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('color', models.CharField(default='white', max_length=30)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('link', models.URLField(default='www.naver.com', max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
