# Generated by Django 2.1.1 on 2018-11-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
